### ISSUE TITLE
Global function KeyaddrErrorHandler not detected

### ISSUE THREAD

**Issue by anhcao142** [ndau/ndaujs#9]
Hi, I'm getting this warning every time I use `await ndau.initKeyaddr();`. It's not critical but It's kind of annoying and I couldn't find a way to temporarily turn it off.

Reproduce code

```Javascript
const ndau = require('@ndau/ndaujs');

async function main() {
  await ndau.initKeyaddr(console.log);
}

main().catch(console.log);
```

Here is what it looks like in the console
```
Global function KeyaddrErrorHandler not detected. Adding default error handler function. To override, instantiate KeyaddrErrorHandler early in the JS code.
```

**Comment by jsgjnr** [comment]
We will look at either removing this message or modifying it to be more helpful.  We will update you when a new package is available that includes this change.

-- John
